# Generated by Django 4.0.5 on 2023-05-12 09:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='event',
            field=models.ManyToManyField(through='Articles.Event_Article', to='Articles.event'),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ManyToManyField(through='Articles.Article_User', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ManyToManyField(through='Articles.Event_User', to=settings.AUTH_USER_MODEL),
        ),
    ]
